### PR TITLE
Update Tools.java

### PR DESCRIPTION
**Pull request by fawazahmed0**
Some recovery.img have default.prop named as prop.default

### CODE REVIEW

**Comment by fawazahmed0** [comment]
Some recovery.img have default.prop named as prop.default

**Comment by fawazahmed0** [comment]
Write code accordingly, because some recoveries will have default.prop, prop.default and also build.prop in the same recovery.img, but only one file will have readable text, others will be binary files or might not contain data, this was the case in my recovery.img

**Comment by androidlover5842** [comment]
why closed?

**Comment by fawazahmed0** [comment]
@androidlover5842 see this: https://github.com/TwrpBuilder/twrpbuilder_tree_generator/issues/11#issuecomment-483044088

**Pull request closed without merging**
